"""init schema

Revision ID: 2fb0f999e545
Revises: 
Create Date: 2026-04-11 00:12:39.365077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb0f999e545'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('Planning', 'Active', 'On Hold', 'Completed', name='project_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive', name='role_status'), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sla_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('severity', sa.Enum('Blocker', 'Critical', 'Major', 'Minor', 'Trivial', name='sla_severity'), nullable=False),
    sa.Column('target_hours', sa.Integer(), nullable=False),
    sa.Column('auto_escalate', sa.Boolean(), nullable=False),
    sa.Column('escalation_delay_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('severity')
    )
    op.create_table('employees',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('nip', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('organization', sa.String(length=180), nullable=False),
    sa.Column('unit_organization', sa.String(length=180), nullable=False),
    sa.Column('position', sa.String(length=180), nullable=False),
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive', name='employee_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nip')
    )
    op.create_table('issues',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('severity', sa.Enum('Blocker', 'Critical', 'Major', 'Minor', 'Trivial', name='issue_severity'), nullable=False),
    sa.Column('status', sa.Enum('Open', 'Investigating', 'In Progress', 'Escalated', 'Resolved', name='issue_status'), nullable=False),
    sa.Column('reporter', sa.String(length=140), nullable=False),
    sa.Column('assignee', sa.String(length=140), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('module', sa.String(length=180), nullable=False),
    sa.Column('environment', sa.String(length=180), nullable=False),
    sa.Column('reproduction_steps', sa.JSON(), nullable=False),
    sa.Column('actual_result', sa.Text(), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issues_project_id'), ['project_id'], unique=False)

    op.create_table('phases',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phases_project_id'), ['project_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('priority', sa.Enum('Low', 'Medium', 'High', 'Critical', name='task_priority'), nullable=False),
    sa.Column('assignee', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('phase_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_phase_id'), ['phase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('role_id', sa.String(length=32), nullable=True),
    sa.Column('employee_id', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_phase_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('phases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phases_project_id'))

    op.drop_table('phases')
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_project_id'))

    op.drop_table('issues')
    op.drop_table('employees')
    op.drop_table('sla_rules')
    op.drop_table('roles')
    op.drop_table('projects')
    # ### end Alembic commands ###
